//REGISTER ACTIONS
export const REG_REQUEST = "REG_REQUEST";
export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAILURE = "REG_FAILURE";
//LOGIN ACTIONS
export const LOG_REQUEST = "LOG_REQUEST";
export const LOG_SUCCESS = "LOG_SUCCESS";
export const LOG_FAILURE = "LOG_FAILURE";

//TRIP ACTION
export const CREATE_TRIP_REQUEST = "CREATE_TRIP_REQUEST";
export const CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS";
export const CREATE_TRIP_FAILURE = "CREATE_TRIP_FAILURE";

//PERSON ACTION
export const CREATE_PERSON_REQUEST = "CREATE_PERSON_REQUEST";
export const CREATE_PERSON_SUCCESS = "CREATE_PERSON_SUCCESS";
export const CREATE_PERSON_FAILURE = "CREATE_PERSON_FAILURE";

//EXPENSE ACTION
export const CREATE_EXPENSE_REQUEST = "CREATE_EXPENSE_REQUEST";
export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAILURE = "CREATE_EXPENSE_FAILURE";
